openapi: 3.0.3
info:
  title: Virtual Video Game Events
  description: Serverless API for virtual events video game events
  version: 1.0.0

x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
    validateRequestParameters: true
  params-only:
    validateRequestBody: false
    validateRequestParameters: true

paths:
  /createUser:
    post:
      summary: create user.
      x-amazon-apigateway-request-validator: "all"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestUserBody'
      responses:
        "201":
          description: successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessfulResponse"
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: "POST"
        uri: 
          arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:CreateUserFunction/invocations
        credentials:
          arn:${AWS::Partition}:iam::${AWS::AccountId}:role/ApiGatewayDefaultRole
        passthroughBehaviour: "when_no_match"
  /readTodo/{userId}:
    get:
      summary: Returns the To Do with the specified id.
      #x-amazon-apigateway-request-validator: "params-only"
      parameters:
        - in: path
          name: userId
          #required: true
          schema:
            type: integer
            minimum: 1
      responses:
        "200":
          description: The To Do record.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessfulResponseData"
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: "POST"
        uri: 
          arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:ReadUserFunction/invocations
        credentials:
          arn:${AWS::Partition}:iam::${AWS::AccountId}:role/ApiGatewayDefaultRole
        passthroughBehaviour: "when_no_match"
components:
  schemas:
    RequestUserBody:
      required:
        - userId
        - userName
        - userType
      type: object
      properties:
        userId:
          type: string
        userName:
          type: string
        userType:
          type: string
    SuccessfulResponse:
      required:
        - detail
      type: object
      properties:
        detail:
          type: string
    SuccessfulResponseData:
      type: object
      properties:
        userId:
          type: string
        userName:
          type: string
        userType:
          type: string
